### ISSUE TITLE
Add tests to make sure the only plausible reason a build may fail is due to user mistakes

### ISSUE THREAD

**Issue by CasperWA** [aiidalab/aiidalab-registry#21]
As an extension of #19, tests can now be added using `pytest` that make sure a build only plausably fails due to missing information from a user/app-developer.

**Comment by csadorf** [comment]
@CasperWA Is this issue resolved by merge #48 ?

**Comment by CasperWA** [comment]
> @CasperWA Is this issue resolved by merge #48 ?

I guess. Looking over the touched files from a year and half back together with yours just now the tests cover very different grounds. One being for the build of the website and yours being for the actual changes a user may introduce in this repository.
Hence, since I don't really have the overview of the whole repository, I couldn't say whether these two test suites together encompass everything for this repository. But again, I would guess.

**Comment by csadorf** [comment]
I honestly am not 100% sure how to interpret this issue and since you created it I thought you would know. It appears that there are tests for the website build and for the schema validation now. What else would you like to test?

**Comment by CasperWA** [comment]
My analysis of this would be the following then: If the tests for the schemas cover checking any changes to the JSON files performed by developers in future PRs, then we should have covered everything. Since the website tests will make sure the value of the passed URLs are valid.
I.e., if you are confident of the first, then feel free to close this issue on this basis, since the original issue will indeed have been fixed :smiley: :muscle:

**Comment by csadorf** [comment]
I noticed that the apps_meta.json as it is generated right is not valid according to our schema. That is because apps_meta **is in fact not just a combination of the apps.json and categories.json** files, but includes additional fields. Since this went unnoticed I will add tests that will both cover the published data and schemas as well as the generate apps_meta.json file. Then we can close this issue.

**Comment by csadorf** [comment]
I noticed that the apps_meta.json as it is generated right is not valid according to our schema. That is because apps_meta **is in fact not just a combination of the apps.json and categories.json** files, but includes additional fields. Since this went unnoticed I will add tests that will both cover the published data and schemas as well as the generate apps_meta.json file. Then we can close this issue.
