### ISSUE TITLE
combine app.json with package-specific metadata

### ISSUE THREAD

**Issue by yakutovicha** [aiidalab/aiidalab-registry#6]
apps.json contains very basic information about the package. Would be nice to combine it with more info coming from the package metadata file (it can contain logo, authors, etc..)

**Comment by ltalirz** [comment]
As discussed, one could pull in this information when the app registry is generated...

**Comment by ltalirz** [comment]
Following our discussion today:
Yes, there is a way to trigger builds automatically via the Github API
https://developer.github.com/v3/repos/pages/#request-a-page-build
(currently in "development preview" mode but let's hope it becomes production)

 * We can have a cron-job on some server that POSTS to this endpoint every now and then.
 * We can even add [web hooks](https://github.com/aiidalab/aiidalab-home/settings/hooks/new) to our applications in order to trigger a rebuild of the app index whenever the app is updated
